# Change these first
owner: Revolugo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Booking API
    url: https://booking-api.staging.revolugo.com/health
  - name: Graphql API
    url: https://graphql-api.staging.revolugo.com/health
  - name: Elements
    url: https://elements.revolugo.com
  - name: Elements Vue2
    url: https://elements-vue2.revolugo.com
  - name: Elements Vue3
    url: https://elements-vue3.revolugo.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Revolugo status
  introTitle: "**Revolugo**: Booking platform for your events"
  introMessage: This is the official status page of Revolugo services
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.revolugo.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
